### ISSUE TITLE
Notes: Lab meeting and task delegation

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/group10-worldcovid-dashpython#17]
Notes from our group meeting Tuesday Mar 1 2022:

**Discussion**
- we will be using Thomas' skeleton to create the main dashboard (reviewed this together)
- Adam suggested using monthly interval for date filter
- update the column names to be more readable in the filters using a dictionary with human readable keys
- potentially update the country map animation to not include the date labels on the slider, and opt for the singular date:
<img width="372" alt="Screen Shot 2022-03-01 at 2 22 03 PM" src="https://user-images.githubusercontent.com/69618055/156258861-f31d37cf-5ede-44b6-aa4a-ccae01ad2873.png">

Dashboard changes:
- ALL TABS
      - 3 global filters that effect all charts on both tabs: Date slider, log/linear, country
- Tab 1 (Map and 1 Chart)
      - map and complement line chart
      - 1 variable filter that effects those charts
- Tab 2 (2 static Charts)
      - 1 stacked bar chart (no variable filter)
      - 1 other chart (no variable filter)

**Tasks:**
- [x] frame out design with sketch using bootstrap (@khbunyan)
- [x] Refine get data and filter function (update the column names) (@thomassiu )
- [x] refine the mark display on the date slider to be monthly (@thomassiu and @khbunyan )
- [x] refine the animation slider to remove the date display (as described above) (@adammorphy )
- [x] change map to filter based on selected countries (DONE - @thomassiu  to confirm)
- [x] add vaccination tab with 2 static variable charts (stacked bar chart) (@adammorphy  + @Kingslin0810 )
- [x] update the README (everyone - @khbunyan  to refine)
- [x] write the reflection (@Kingslin0810 )
- [x] submission (@thomassiu )
