### ISSUE TITLE
Milestone 3 tasks

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/group10-worldcovid-dashpython#36]
- [x] Add a Dockerfile and a docker-compose.yml **(Kristin)**
- [x] Write clear instructions at the end of the README.md on how to run the app locally **(Kristin)**
- [x] Add a favicon to the app **(Kristin)**
- [x] Add a title to the app **(Thomas)**
- [x] Peer review **(Kristin)**
- [x] Compare technologies and assign a PR to the respective md, i.e. group_10.md [here](https://github.com/UBC-MDS/dash-tableau-shiny_comparison) **(Adam)** **(Kingslin)**

Check other items in [R repo](https://github.com/UBC-MDS/group10-worldcovid-dash-r).
