### ISSUE TITLE
Meeting for Milestone 4

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/group10-worldcovid-dashpython#43]
5+ changes for updates
- [x] change current to daily @khbunyan 
      - link: python: [8665716](https://github.com/UBC-MDS/group10-worldcovid-dashpython/pull/42/commits/866571654b0bae15b6a52b7b7524057d68dd3b6c)
      - R: [2645e32](https://github.com/UBC-MDS/group10-worldcovid-dash-r/pull/12/commits/2645e320115df1be36f07c2a3c35d4cd84c5f2bf)
- [x] description log/linear @khbunyan 
      - links "python": [e320e47](https://github.com/UBC-MDS/group10-worldcovid-dashpython/pull/46/commits/e320e4726da0e5d867b396ffe77b5cb6125376e8)
      - links "r": https://github.com/UBC-MDS/group10-worldcovid-dash-r/commit/b6e695ac31a4bc6c32b786e2df2aeacd830433fa, https://github.com/UBC-MDS/group10-worldcovid-dash-r/commit/5c2ad2da6fc88a75d792f7c258381c2de79804f2
- [x] description to date slider @khbunyan 
       - links: python: [e320e47](https://github.com/UBC-MDS/group10-worldcovid-dashpython/pull/46/commits/e320e4726da0e5d867b396ffe77b5cb6125376e8)
       - link: https://github.com/UBC-MDS/group10-worldcovid-dash-r/commit/b6e695ac31a4bc6c32b786e2df2aeacd830433fa, https://github.com/UBC-MDS/group10-worldcovid-dash-r/commit/5c2ad2da6fc88a75d792f7c258381c2de79804f2
- [x] containerize the plots @thomassiu  
       - link: python: [17b634d](https://github.com/UBC-MDS/group10-worldcovid-dashpython/pull/47/commits/17b634d3132d26111b5b9c9baba413ff53f069dd)
- [x] add scatter points with rolling averages @adammorphy 
      - link: python: [8a6357f](https://github.com/UBC-MDS/group10-worldcovid-dashpython/pull/44/commits/8a6357fa97e6f8bc866146f763245ce8ee0c968e)
- [x] reference and links to data repo @Kingslin0810 
       - link: python: [b8db1a3](https://github.com/UBC-MDS/group10-worldcovid-dashpython/pull/45/commits/b8db1a35f862b6ea6eed6ad93316e97b5c4c00aa)
- [x] format (left align) to dashboard description @adammorphy 
       - link: python: [b8db1a3](https://github.com/UBC-MDS/group10-worldcovid-dashpython/commit/b8db1a35f862b6ea6eed6ad93316e97b5c4c00aa)
- [x] format legend (re-name/remove data column names) @Kingslin0810 
       - link: python: [a7819b1](https://github.com/UBC-MDS/group10-worldcovid-dashpython/pull/45/commits/a7819b1364c5b3ea3079f27ebaf5258d392814f7)
- [x] description to country selector @thomassiu 
       - link: python: [17b634d](https://github.com/UBC-MDS/group10-worldcovid-dashpython/pull/47/commits/17b634d3132d26111b5b9c9baba413ff53f069dd) 
       - R: [bcf11f7](https://github.com/UBC-MDS/group10-worldcovid-dash-r/pull/19/commits/bcf11f711066227342d6e4b2c39ae2a38bc5c71e)
- [x] Add favicon and app title to R app @thomassiu 
       - link: R: [1206350](https://github.com/UBC-MDS/group10-worldcovid-dash-r/pull/21/commits/120635089a221e7f59f0e6edb515e5d99f332cad)

Reflection
- [x] Filter by continents in both python and R was not done due to time constraints and performance considerations.
- [x] There is still performance issue in the R version of app when loading the charts, even we have used a smaller dataset and grouped them as one callback. It is still under investigation on how to further improve the loading time for R.
- [x] Last updated data can be added in the footer
- [x] In future releases we can also make the app more responsive, i.e. to dynamically change the size of the sidebars, charts and overall size of the content based on the browser window size. It helps people to assess our webpage in different browser size and even on mobile app.

R readme update
- [x] make gif @khbunyan 
   - link: https://github.com/UBC-MDS/group10-worldcovid-dash-r/commit/e9a5a7712bee78bad72fa1e5532c5467832724b2
   - link: https://github.com/UBC-MDS/group10-worldcovid-dash-r/commit/1150c59ed65915a4ae6c79e41c376e5e01459214
- [x] update wording and links @khbunyan 
    - link "r": https://github.com/UBC-MDS/group10-worldcovid-dash-r/commit/7bda4ffbbe87c2eb22af89615ed912d832b85361

Heroku
- [x] finished/deployed to check for Python
- [x] finished/deployed to check for R
